### ISSUE TITLE
是一个没见过的字幕组？

### ISSUE THREAD

**Issue by zzzwannasleep** [vanilla-translation-group/subtitles#1]
如果是新人字幕组 那么加油加油再加油 你们真的很棒 太开心有新血液加入进来了
如果是以前的字幕组 那我祝你们源远流长 多彩多样 加油！

**Comment by baiyuanneko** [comment]
感谢支持！
![image](https://github.com/user-attachments/assets/d4058ecf-5451-438b-9691-70d6e30b9df3)
